---
name: Docker Build

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:

  build-jekyll-image:

    # use Reusable Workflows
    # https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
    name: Call Docker Build Jekyll1

    uses: bretfisher/docker-build-workflow/.github/workflows/reusable-docker-build.yaml@v1

    permissions:
      contents: read
      packages: write # needed to push docker image to ghcr.io
      pull-requests: write # needed to create and update comments in PRs
    
    secrets:

      dockerhub-username: xiquwugou
      dockerhub-token: dckr_pat_iKFizpU079xDqOejSDOJ1V0VWRY

    with:
      dockerhub-enable: true
      ghcr-enable: true
      image-names: |
        xiquwugou/xia90
      platforms: linux/amd64,linux/arm64,linux/arm/v7

#  build-jekyll-serve-image:
#
#    # use Reusable Workflows
#    # https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
#    name: Call Docker Build Jekyll-Serve
#
#    uses: bretfisher/docker-build-workflow/.github/workflows/reusable-docker-build.yaml@main
#
#    needs: build-jekyll-image
#
#    # if: github.event_name == 'push'
#
#    permissions:
#      contents: read
#      packages: write # needed to push docker image to ghcr.io
#      pull-requests: write # needed to create and update comments in PRs
#
#    secrets:
#
#      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
#      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
#
#    with:
#      dockerhub-enable: true
#      ghcr-enable: true
#      image-names: |
#        bretfisher/jekyll-serve
#        ghcr.io/bretfisher/jekyll-serve
#      platforms: linux/amd64,linux/arm64,linux/arm/v7
#      target: jekyll-serve
